steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/notes-be114:v1", "."]
    dir: "Backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/notes-be114:v1"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "notes-be114",
        "--image",
        "gcr.io/$PROJECT_ID/notes-be114:v1",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
