steps:
  # 1. Build Docker image dengan tag unik (berdasarkan commit ID)
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/notes-be114:$SHORT_SHA", "."]
    dir: "Backend"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/notes-be114:$SHORT_SHA"]

  # 3. Deploy ke Cloud Run pakai image yang ditag unik
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "notes-be114",
        "--image",
        "gcr.io/$PROJECT_ID/notes-be114:$SHORT_SHA",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
